# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            python-version: 3.9.12
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r $(git ls-files '*requirements.txt')
    - name: freeze exe
      run: "./build-dist.ps1 ${{github.workspace}}\\src\\pyside2"
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        path:  ${{github.workspace}}\\src\\pyside2\\dist
        name: ${{ matrix.os }}
